const {test}=require('node:test'),assert=require('node:assert/strict');const {boot}=require('./harness.cjs');
function empty(g,changes={}){const L={...g.levels[0],walls:[],hazards:[],keys:[],fixed:[],switches:[],gates:[],portals:[],fragile:[],oneWay:[],limited:[],links:[],autoRotate:[],movers:[],decoys:[],exit:[0,5],ordered:false,...changes};g.openLevel(0);let S=g.cloneRun(g.state);S.L=L;S.grid=Array.from({length:7},()=>Array(6).fill('R'));S.pos=[3,2];return S}
test('fresh play starts at level 1, remaining levels are locked',()=>{const {g,el}=boot();assert.equal(g.save.lastLevel,0);assert.equal(g.save.unlocked,1);el('#playBtn').listeners.click();assert.equal(g.state.L.name,'İlk Kıvılcım')});
test('last level and stars survive reload; reset is consistent',()=>{const a=boot();for(let i=0;i<7;i++)a.g.storeRecord(a.g.levels[i],50,50);a.g.openLevel(7);a.g.state.rotations=0;a.g.win();const b=boot(Object.fromEntries(a.data));assert.equal(b.g.save.lastLevel,8);assert.equal(b.g.save.stars[7],3);b.g.resetAll();const c=boot(Object.fromEntries(b.data));assert.equal(c.g.save.lastLevel,0);assert.equal(c.g.save.unlocked,1);assert.equal(Object.keys(c.g.save.stars).length,0)});
test('invalid stored data cannot break level menu',()=>{const {g}=boot({kh32_stars:'{"0":99,"1":-2,"2":3}',kh32_lastLevel:'NaN'});assert.equal(g.save.lastLevel,0);assert.equal(Object.keys(g.save.stars).length,1)});
test('late result is cancelled on restart and navigation',()=>{const {g,scheduled,el}=boot();g.openLevel(0);g.fail('test');g.openLevel(0);for(const cb of scheduled.values())cb();assert.equal(g.state.dead,false);g.fail('test');g.show('levels');for(const cb of scheduled.values())cb();assert.equal(el('#resultOverlay').classList.contains('show'),false)});
test('rotation undo restores resources and linked arrows',()=>{const {g}=boot();for(let i=0;i<20;i++)g.storeRecord(g.levels[i],50,50);g.openLevel(20);const before=JSON.stringify(g.state.grid),moves=g.state.moves;g.rotate(...g.state.L.links[0][0]);assert.equal(g.state.moves,moves+1);g.undoRotation();assert.equal(JSON.stringify(g.state.grid),before);assert.equal(g.state.moves,moves);assert.equal(g.state.rotations,0)});
test('gate preserves incoming direction; closed gate blocks',()=>{const {g}=boot();let S=empty(g,{gates:[[3,3,'A']]});assert.match(g.advance(S).reason,/kapalı/i);S.openGates.add('A');S.grid[3][3]='U';assert.equal(g.advance(S).reason,null);assert.equal(S.grid[3][3],'R');g.advance(S);assert.equal(JSON.stringify(S.pos),'[3,4]')});
test('patrol current occupancy and next occupancy both collide',()=>{const {g}=boot();let S=empty(g,{movers:[{path:[[3,3],[3,4]]}]});assert.match(g.advance(S).reason,/Devriye/);S=empty(g,{movers:[{path:[[3,4],[3,3]]}]});assert.match(g.advance(S).reason,/Devriye/)});
test('preview warns before start including patrol and missing keys',()=>{const {g}=boot();g.state=empty(g,{movers:[{path:[[3,3],[3,4]]}]});let p=g.predictRoute(1);assert.equal(JSON.stringify(p.danger),'[3,3]');g.state=empty(g,{keys:[[0,0]],exit:[3,3]});p=g.predictRoute(1);assert.match(p.reason,/anahtarların eksik/)});
test('ordered keys, portals and automatic rotation share actual rules',()=>{const {g}=boot();let S=empty(g,{keys:[[1,1],[3,3]],ordered:true});assert.match(g.advance(S).reason,/sırası yanlış/);S=empty(g,{portals:[{a:[3,3],b:[1,1]}],keys:[[1,1]],autoRotate:[[1,1]]});assert.equal(g.advance(S).portaled,true);assert.equal(S.collected.size,1);assert.equal(S.grid[1][1],'D')});
test('fragile tile collapses after leaving; switch toggles gate',()=>{const {g}=boot();let S=empty(g,{fragile:[[3,2]],switches:[[3,3,'A']]});g.advance(S);assert.ok(S.openGates.has('A'));S.grid[3][3]='L';assert.match(g.advance(S).reason,/çökmüştü/)});
test('background pause and restart reset pause icon',()=>{const {g,doc,el}=boot();g.openLevel(0);g.startGame();doc.hidden=true;doc.visibilitychange();assert.equal(g.state.paused,true);g.openLevel(0);assert.equal(el('#pauseBtn').attrs['aria-label'],'Duraklat');assert.equal(g.state.paused,false)});
test('hint after result cannot change stars',()=>{const {g,el}=boot();g.openLevel(0);g.win();el('#hintBtn').listeners.click();assert.equal(g.state.hintUsed,false)});

test('ice cannot be rotated and preserves incoming direction',()=>{const {g}=boot();let S=empty(g,{ice:[[3,3]]});S.grid[3][3]='U';g.state=S;g.rotate(3,3);assert.equal(S.moves,0);assert.equal(S.grid[3][3],'U');assert.equal(g.advance(S).reason,null);assert.equal(S.grid[3][3],'R');g.advance(S);assert.equal(JSON.stringify(S.pos),'[3,4]')});
test('phase switch opens II, closes I; gates preserve direction and reject edits',()=>{const {g}=boot();let S=empty(g,{phaseSwitches:[[3,3]],phaseGates:[[3,4,1],[3,5,0]]});g.state=S;assert.equal(g.advance(S).reason,null);assert.equal(S.phase,1);S.grid[3][4]='U';g.rotate(3,4);assert.equal(S.moves,0);assert.equal(g.advance(S).reason,null);assert.equal(S.grid[3][4],'R');assert.match(g.advance(S).reason,/Faz I/)});
test('inactive phase gate blocks and phase is part of cycle state',()=>{const {g}=boot();let S=empty(g,{phaseGates:[[3,3,1]]});assert.match(g.advance(S).reason,/Faz II/);let token=g.runToken(S);S.phase=1;assert.notEqual(token,g.runToken(S));assert.equal(g.advance(S).reason,null)});
test('phase preview agrees with actual movement without mutating the board',()=>{const {g}=boot();g.state=empty(g,{phaseSwitches:[[3,3]],phaseGates:[[3,4,1]],exit:[3,5]});const before=JSON.stringify([g.state.grid,g.state.pos,g.state.phase]);const p=g.predictRoute();assert.equal(p.danger,null);assert.equal(JSON.stringify([g.state.grid,g.state.pos,g.state.phase]),before);g.startGame();g.tick();g.tick();g.tick();assert(g.state.won)});
test('all 74 layouts differ structurally and introduce mechanisms gradually',()=>{const {g}=boot();const signatures=g.levels.map(L=>JSON.stringify([L.walls,L.start,L.exit,L.keys,L.portals]));assert.equal(new Set(signatures).size,74);assert(g.levels[25].ice.length);assert(g.levels[30].phaseGates.length);assert.equal(g.levels[40].portals.length,2);for(const L of g.levels){assert.equal(L.layout.length,7);assert(L.layout.every(row=>row.length===6&&row.every(d=>'URDL'.includes(d))));for(const p of [L.start,L.exit,...L.keys])assert(!L.walls.some(w=>w[0]===p[0]&&w[1]===p[1]));}});

test('all 42 cells in every level are filled, with 3–6 ordered keys',()=>{const {g,el}=boot();for(let i=0;i<50;i++){if(i)g.storeRecord(g.levels[i-1],50,50);g.openLevel(i);const L=g.state.L;assert.equal(L.walls.length,0);assert.equal(el('#board').children.length,42);assert(L.ordered);assert(L.keys.length>=3&&L.keys.length<=6);}});
test('exit requires the named relay to remain active',()=>{const {g}=boot();let S=empty(g,{exit:[3,3],requiredGates:['A']});assert.match(g.advance(S).reason,/rölesini/);S=empty(g,{exit:[3,3],requiredGates:['A']});S.openGates.add('A');assert.equal(g.advance(S).won,true);});
test('required-relay exit warning is present in preview too',()=>{const {g}=boot();g.state=empty(g,{exit:[3,3],requiredGates:['A']});assert.match(g.predictRoute(1).reason,/rölesini/);assert.equal(g.state.openGates.size,0);});
test('independent relaxed shortest paths confirm the campaign movement floors',()=>{const {g}=boot();const same=(a,b)=>a[0]===b[0]&&a[1]===b[1];function dist(L,a,b){const q=[[a,0]],seen=new Set([a.join(',')]);for(let i=0;i<q.length;i++){const[p,d]=q[i];if(same(p,b))return d;for(const [dr,dc]of [[-1,0],[0,1],[1,0],[0,-1]]){let z=[p[0]+dr,p[1]+dc];if(z[0]<0||z[0]>6||z[1]<0||z[1]>5||L.hazards.some(x=>same(x,z)))continue;for(const pair of L.portals){if(same(z,pair.a)){z=pair.b;break}if(same(z,pair.b)){z=pair.a;break}}const k=z.join(',');if(!seen.has(k)){seen.add(k);q.push([z,d+1])}}}return Infinity;}let previous=0;for(const L of g.levels){const stops=[L.start,...L.keys,L.exit];let sum=0;for(let i=1;i<stops.length;i++)sum+=dist(L,stops[i-1],stops[i]);assert.equal(sum,L.balance.relaxedSteps);assert(sum>=16&&sum>=previous);assert(sum<=L.balance.referenceSteps);previous=sum;}});

test('master world requires every normal level, not only level 50',()=>{const {g}=boot();assert(!g.masterUnlocked());assert(!g.canPlay(50));g.storeRecord(g.levels[49],50,50);assert(!g.masterUnlocked());assert(!g.canPlay(49));assert.equal(g.openLevel(50),false);for(let i=0;i<49;i++)g.storeRecord(g.levels[i],100,50);assert(g.masterUnlocked());g.openLevel(50);assert.equal(g.state.L.id,'kh40-master-01');});
test('unlock survives reload and reset relocks master world',()=>{const a=boot();for(let i=0;i<50;i++)a.g.storeRecord(a.g.levels[i],50,50);a.g.openLevel(50);const b=boot(Object.fromEntries(a.data));assert(b.g.masterUnlocked());assert.equal(b.g.save.lastLevel,50);b.g.resetAll();assert(!b.g.masterUnlocked());assert(!b.g.canPlay(50));});
test('stale master last-level save cannot bypass the lock',()=>{const {g}=boot({kh32_lastLevel:'70'});assert.equal(g.save.lastLevel,0);assert.equal(g.save.unlocked,1);});
test('single-step advances exactly once, pauses and allows rotation undo',()=>{const {g,el}=boot();g.state=empty(g,{exit:[3,5]});g.singleStep();assert.equal(g.state.steps,1);assert(g.state.running&&g.state.paused);assert.equal(g.state.pos[1],3);const before=g.state.moves;g.rotate(2,2);assert.equal(g.state.moves,before+1);g.undoRotation();assert.equal(g.state.moves,before);g.singleStep();assert.equal(g.state.steps,2);assert.equal(g.state.pos[1],4);assert(el('#stepBtn').disabled===false);g.singleStep();assert(g.state.won);assert(el('#stepBtn').disabled);});
test('single-step does not recollect a switch and is disabled during auto run',()=>{const {g}=boot();g.state=empty(g,{switches:[[3,2,'A']],exit:[3,5]});g.singleStep();assert(g.state.openGates.has('A'));g.singleStep();assert(g.state.openGates.has('A'));g.pauseGame();const count=g.state.steps;g.singleStep();assert.equal(g.state.steps,count);});
test('master exit needs both crystals and the correct phase',()=>{const {g}=boot();let S=empty(g,{exit:[3,3],requiredCrystals:true,phaseSwitches:[[1,1],[2,2]],exitPhase:0});assert.match(g.advance(S).reason,/kristaline/);S=empty(g,{exit:[3,3],requiredCrystals:true,phaseSwitches:[[1,1],[2,2]],exitPhase:0});S.visitedCrystals=new Set(['1,1','2,2']);S.phase=1;assert.match(g.advance(S).reason,/Faz I/);S.pos=[3,2];S.phase=0;assert(g.advance(S).won);});
test('preview crystal collection is isolated from the live state',()=>{const {g}=boot();g.state=empty(g,{phaseSwitches:[[3,3]],exit:[3,5]});g.predictRoute();assert.equal(g.state.visitedCrystals.size,0);});
test('master layouts are full and have tougher verified movement floors',()=>{const {g}=boot();const hardestNormal=Math.max(...g.levels.slice(0,50).map(L=>L.balance.relaxedSteps));for(const L of g.levels.slice(50)){assert.equal(L.walls.length,0);assert(L.balance.relaxedSteps>hardestNormal);assert(L.keys.length>=8);assert.deepEqual(Array.from(L.requiredGates),['A','B']);assert.equal(L.phaseSwitches.length,2);assert.equal(L.links.length,2);}});

test('start hints match verified routes and do not alter player moves or grid',()=>{
 const {g,el}=boot();const routes=JSON.parse(require('node:fs').readFileSync(require('node:path').join(__dirname,'solutions.json'),'utf8'));
 g.levels.forEach(L=>g.save.records[L.id]={moves:100,steps:100});
 for(let i=0;i<74;i++){
  g.openLevel(i);const before=JSON.stringify(g.state.grid),moves=g.state.moves;
  el('#hintBtn').listeners.click();
  assert.equal(g.state.showStartHint,true);assert.equal(JSON.stringify(g.state.grid),before);assert.equal(g.state.moves,moves);
  const [a,b]=routes[i].path;assert.equal(Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1]),1);
  const highlighted=el('#board').children.filter(t=>t.classes.has('hint-next'));
  assert.equal(highlighted.length,1);assert.equal(highlighted[0].dataset.r,b[0]);assert.equal(highlighted[0].dataset.c,b[1]);
  el('#hintBtn').listeners.click();assert.equal(g.state.showStartHint,false);
 }
});
test('hint pauses automatic movement without resetting the run',()=>{
 const {g,el}=boot();g.openLevel(0);g.startGame();const pos=JSON.stringify(g.state.pos);
 el('#hintBtn').listeners.click();assert.equal(g.state.paused,true);assert.equal(JSON.stringify(g.state.pos),pos);assert.equal(g.state.showStartHint,true);
});

test('sequential locks reject skipped levels and unlock exactly one successor',()=>{const {g}=boot();assert(g.canPlay(0));assert(!g.canPlay(1));assert.equal(g.openLevel(5),false);g.openLevel(0);g.win();assert(g.canPlay(1));assert(!g.canPlay(2));g.storeRecord(g.levels[3],10,10);assert(!g.canPlay(4));});

test('Android back follows visited screens and confirms exit only on home',()=>{
 const {g,el}=boot({kh32_seenHelp:'1'});
 g.show('levels');g.openLevel(0);g.handleAndroidBack();assert(el('#levels').classList.contains('active'));g.handleAndroidBack();assert(el('#home').classList.contains('active'));assert(!el('#exitOverlay').classList.contains('show'));
 g.show('settings');g.handleAndroidBack();assert(el('#home').classList.contains('active'));g.handleAndroidBack();assert(el('#exitOverlay').classList.contains('show'));g.handleAndroidBack();assert(!el('#exitOverlay').classList.contains('show'));
 g.openLevel(0);g.handleAndroidBack();assert(el('#home').classList.contains('active'));
});
test('Android back closes help before navigating and stops a running game',()=>{
 const {g,el}=boot({kh32_seenHelp:'1'});g.show('settings');el('#helpBtn').listeners.click();g.handleAndroidBack();assert(!el('#helpOverlay').classList.contains('show'));assert(el('#settings').classList.contains('active'));
 g.show('home');g.openLevel(0);g.startGame();g.handleAndroidBack();assert(!g.state.running);assert(el('#home').classList.contains('active'));
});
