const {test}=require('node:test'),assert=require('node:assert/strict');const {boot}=require('./harness.cjs');
function empty(g,changes={}){const L={...g.levels[0],walls:[],hazards:[],keys:[],fixed:[],switches:[],gates:[],portals:[],fragile:[],oneWay:[],limited:[],links:[],autoRotate:[],movers:[],decoys:[],exit:[0,5],ordered:false,...changes};g.openLevel(0);let S=g.cloneRun(g.state);S.L=L;S.grid=Array.from({length:7},()=>Array(6).fill('R'));S.pos=[3,2];return S}
test('fresh play starts at level 1, all 24 remain available',()=>{const {g,el}=boot();assert.equal(g.save.lastLevel,0);assert.equal(g.save.unlocked,24);el('#playBtn').listeners.click();assert.equal(g.state.L.name,'İlk Akış')});
test('last level and stars survive reload; reset is consistent',()=>{const a=boot();a.g.openLevel(7);a.g.state.rotations=0;a.g.win();const b=boot(Object.fromEntries(a.data));assert.equal(b.g.save.lastLevel,8);assert.equal(b.g.save.stars[7],3);b.g.resetAll();const c=boot(Object.fromEntries(b.data));assert.equal(c.g.save.lastLevel,0);assert.equal(c.g.save.unlocked,24);assert.equal(Object.keys(c.g.save.stars).length,0)});
test('invalid stored data cannot break level menu',()=>{const {g}=boot({kh9_stars:'{"0":99,"1":-2,"2":3}',kh9_lastLevel:'NaN'});assert.equal(g.save.lastLevel,0);assert.equal(Object.keys(g.save.stars).length,1)});
test('late result is cancelled on restart and navigation',()=>{const {g,scheduled,el}=boot();g.openLevel(0);g.fail('test');g.openLevel(1);for(const cb of scheduled.values())cb();assert.equal(g.state.dead,false);g.fail('test');g.show('levels');for(const cb of scheduled.values())cb();assert.equal(el('#resultOverlay').classList.contains('show'),false)});
test('rotation undo restores resources and linked arrows',()=>{const {g}=boot();g.openLevel(10);const before=JSON.stringify(g.state.grid),moves=g.state.moves;g.rotate(5,1);assert.equal(g.state.moves,moves-1);g.undoRotation();assert.equal(JSON.stringify(g.state.grid),before);assert.equal(g.state.moves,moves);assert.equal(g.state.rotations,0)});
test('gate preserves incoming direction; closed gate blocks',()=>{const {g}=boot();let S=empty(g,{gates:[[3,3,'A']]});assert.match(g.advance(S).reason,/kapalı/i);S.openGates.add('A');S.grid[3][3]='U';assert.equal(g.advance(S).reason,null);assert.equal(S.grid[3][3],'R');g.advance(S);assert.equal(JSON.stringify(S.pos),'[3,4]')});
test('patrol current occupancy and next occupancy both collide',()=>{const {g}=boot();let S=empty(g,{movers:[{path:[[3,3],[3,4]]}]});assert.match(g.advance(S).reason,/Devriye/);S=empty(g,{movers:[{path:[[3,4],[3,3]]}]});assert.match(g.advance(S).reason,/Devriye/)});
test('preview warns before start including patrol and missing keys',()=>{const {g}=boot();g.openLevel(13);g.state.pos=[3,5];g.state.grid[3][5]='L';let p=g.predictRoute(1);assert.equal(JSON.stringify(p.danger),'[3,4]');g.state=empty(g,{keys:[[0,0]],exit:[3,3]});p=g.predictRoute(1);assert.match(p.reason,/anahtarların eksik/)});
test('ordered keys, portals and automatic rotation share actual rules',()=>{const {g}=boot();let S=empty(g,{keys:[[1,1],[3,3]],ordered:true});assert.match(g.advance(S).reason,/sırası yanlış/);S=empty(g,{portals:[{a:[3,3],b:[1,1]}],keys:[[1,1]],autoRotate:[[1,1]]});assert.equal(g.advance(S).portaled,true);assert.equal(S.collected.size,1);assert.equal(S.grid[1][1],'D')});
test('fragile tile collapses after leaving; switch toggles gate',()=>{const {g}=boot();let S=empty(g,{fragile:[[3,2]],switches:[[3,3,'A']]});g.advance(S);assert.ok(S.openGates.has('A'));S.grid[3][3]='L';assert.match(g.advance(S).reason,/çökmüştü/)});
test('background pause and restart reset pause icon',()=>{const {g,doc,el}=boot();g.openLevel(0);g.startGame();doc.hidden=true;doc.visibilitychange();assert.equal(g.state.paused,true);g.openLevel(0);assert.equal(el('#pauseBtn').attrs['aria-label'],'Duraklat');assert.equal(g.state.paused,false)});
test('hint after result cannot change stars',()=>{const {g,el}=boot();g.openLevel(0);g.win();el('#hintBtn').listeners.click();assert.equal(g.state.hintUsed,false)});
