package tr.kirilmahatti.game;
import android.app.*;import android.content.DialogInterface;import android.os.*;import android.webkit.*;import android.view.*;import android.graphics.Color;
public final class MainActivity extends Activity {
 private WebView web;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(13,20,35));getWindow().setNavigationBarColor(Color.rgb(13,20,35));web=new WebView(this);web.setBackgroundColor(Color.rgb(13,20,35));web.setOnApplyWindowInsetsListener(new View.OnApplyWindowInsetsListener(){public WindowInsets onApplyWindowInsets(View v,WindowInsets insets){v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;}});setContentView(web);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMediaPlaybackRequiresUserGesture(true);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,String u){return !u.equals("https://game.local/index.html");}@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{if("game.local".equals(r.getUrl().getHost())&&"/index.html".equals(r.getUrl().getPath()))return new WebResourceResponse("text/html","UTF-8",getAssets().open("index.html"));}catch(Exception e){}return new WebResourceResponse("text/plain","UTF-8",new java.io.ByteArrayInputStream(new byte[0]));}});web.setWebChromeClient(new WebChromeClient(){@Override public boolean onJsConfirm(WebView v,String u,String message,final JsResult result){new AlertDialog.Builder(MainActivity.this).setMessage(message).setPositiveButton("Tamam",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){result.confirm();}}).setNegativeButton("Vazgeç",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){result.cancel();}}).setOnCancelListener(new DialogInterface.OnCancelListener(){public void onCancel(DialogInterface d){result.cancel();}}).show();return true;}});web.loadUrl("https://game.local/index.html");}
 @Override protected void onPause(){web.evaluateJavascript("document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new Event('pagehide'));",null);web.onPause();super.onPause();}
 @Override protected void onResume(){super.onResume();if(web!=null)web.onResume();}
 @Override public void onBackPressed(){new AlertDialog.Builder(this).setMessage("Oyundan çıkılsın mı?").setNegativeButton("Devam et",null).setPositiveButton("Çık",new DialogInterface.OnClickListener(){public void onClick(DialogInterface d,int w){finish();}}).show();}
}
